### ISSUE TITLE
검색, 장르선택에 따른 게임리스트를 16개 전달 (초기 전달값은 최신 추가된 형태로 전달해야한다.)

### ISSUE THREAD

**Issue by YeChanKang** [QG-LN/Quantum-Tec#53]

**Comment by MayoneJY** [comment]
@YeChanKang 
`시작번호, 끝번호를 받아 게임 이름(포함된), 게임 장르(카테고리), 가격범위 (0을 기준으로 입력받은 값이 max값으로)에 해당하는 게임을 16개의 리스트로 가져오는 쿼리문 필요 (GameSearchResponseDTO 참조)`

1. 시작 번호와 끝 번호를 받는다는 것이 1~16번의 게임들을 받는다는 의미 일까요?
2. 게임 이름(포함된)에 포함된이 무엇인지 이해가 잘 안됩니다.

**Comment by YeChanKang** [comment]
1.현재 스크롤 위치에 맞는 시작번호, 끝번호를 생성하여 데이터를 전달받으면 그 번호를 기준으로 데이터를 불러오는것
ex) 처음 메인페이지 들어오면 1, 16이고, 스크롤을 한번 내리면 17, 32이고, 한번 더 내리면 33, 48을 전달받아 db리스트에서 시작번호와 끝번호 사이의 인덱스를 가진 데이터들을 전달받는 것
2.게임 이름을 자동차 라고 검색했으면 자동차 가 포함된 모든 데이터를 조회하는 것 (like)
