### ISSUE TITLE
게시판 제작을 위한 DB 요청 리스트

### ISSUE THREAD

**Issue by YeChanKang** [QG-LN/Quantum-Tec#64]
## 목적
SQL문 제작 필요
## 작업 상세 내용
#Front
- [x] 이전 글, 다음 글, 목록 기능 구현을 위한 대화의 자리.

#Back( DB )
- [x] 게시판 종류를 공지사항/튜터링/자유게시판 으로 수정해주세요
- [x] 게시글 리스트 불러오기(검색, 정렬 포함) : ListDTO와 ListResponseDTO를 참조하여 BoardDAO의 getPostSearchList 안에 들어갈 값을 불러오는 SQL문을 만들어주세요
- [x] 게시글 조회하기 : ViewDTO와 ViewResponseDTO를 참조하여 BoardDAO의 getPost안에 들어갈 값을 불러오는 SQL문을 만들어주세요 
- [x] 게시글 작성하기 : WriteDTO를 참조하여 BoardDAO의 writePost안에 들어간 값을 사용해 게시글을 작성하는 SQL문을 만들어주세요 (id=writePost)
- [x] 게시글 수정하기 : ModifyDTO를 참조하여 BoardDAO의 modifyPost안에 들어간 값을 사용해 게시글을 수정하는 SQL문을 만들어주세요 (id=modifyPost)
- [x] 게시글 삭제하기 : DeleteDTO를 참조하여 BoardDAO의 deletePost안에 들어간 값을 사용해 게시글을 삭제하는 SQL문을 만들어주세요 (id=deletePost)
- [x] 게시글 추천, 비추천하기 : VoteDTO를 참조하여 BoardDAO의 upvotePost안에 들어간 값을 사용해 게시글을 추천, 비추천, 각각 중복 확인 하는 SQL문을 만들어주세요  (id=upvotePost, downvotePost, checkUpvote, checkDownvote)
- [x] 댓글 리스트 불러오기 (정렬 포함) : CommentListDTO와 CommentListResponseDTO를 참조하여 BoardDAO의 getCommnetList 안에 들어갈 값을 불러오는 SQL문을 만들어 주세요 (id는 DAO의 메서드명과 일치합니다)
- [x] 댓글 작성하기 : CommentWriteDTO를 참조하여 BoardDAO의 writeComment 안에 들어간 값을 사용해 게시글을 작성하는 SQL문을 만들어주세요
- [x] 댓글 수정하기 : CommentModifyDTO를 참조하여 BoardDAO의 modifyComment 안에 들어간 값을 사용해 게시글을 수정하는 SQL문을 만들어주세요
- [x] 댓글 삭제하기 : CommentDeleteDTO를 참조하여 BoardDAO의 deleteComment 안에 들어간 값을 사용해 게시글을 삭제하는 SQL문을 만들어주세요
- [x] 댓글 추천, 비추천하기 : CommentVoteDTO를 참조하여 BoardDAO의 upvoteComment 안에 들어간 값을 사용해 게시글을 추천, 비추천, 각각 중복확인 하는 SQL문을 만들어주세요 (upvoteComment, downvoteComment, checkCommentUpvote, checkCommentDownvote)
- [x] 다음 게시글/이전게시글 : NavigateViewDTO를 참조하여 이전 게시글과 다음 게시글이 존재하는지 여부를 게시판 종류도 함께 받아서 조회하는 SQL문을 만들어주세요 (게시판 종류 : 전체/공지사항/튜터링/자유게시판, 전체 값은 0으로 전달받는걸로)

## 참고사항
게시글 리스트 불러오는 조건
1. pageNum : 현재 페이지 번호 (BoardService 안에서 startIndex, endIndex 계산한뒤 Mapper로 전달)
2. boardIndex : 게시판 종류, 기본값은 0으로 받게 되며 이 경우 게시판을 가리지 않고 모두 가져옴
3. sortType : 정렬기준, 문자열을 반환하는 enum 형태 (최신순, 오래된순, 추천순)
(가장 처음 접속했을 경우, front에서 보내는 값은 정렬 기준만 latest로 받아오는걸로)
4. searchType : 검색기준, 문자열을 반환하는 enum 형태 (제목, 작성자, 제목+작성자)
(if문으로 searchType.equals("title")처럼 활용해서 각 경우를 편하게 나눌 수 있습니다.)
5. searchKeyword : 검색어

댓글 리스트 불러오는 조건
1. pageNum : 프론트로부터 받아올 페이지 카운트
2. startIndex : pageNum 가지고 계산한 가져올 시작 댓글 인덱스
3. endIndex : 총 표시할 댓글 갯수
4. postIndex : 게시글 인덱스
5. sortType : 정렬기준 enum형태 (date, upvote, downvote, rating) 프론트에서 기본값은 date(최신순)으로 받아오는걸로

- front로부터 받아와야하는 값 (여기서 id는 index를 뜻함)
- 게시글 작성
게시판 종류(번호), 작성자id, 제목, 내용
- 게시글 삭제
작성자id, 게시글id
- 게시글 수정
게시판 종류(번호), 게시글id, 작성자id, 제목, 내용
- 게시글 추천/비추천
추천자id, 게시물id
- 댓글 작성
게시글id, 작성자id, 댓글 내용
- 댓글 수정
게시글id, 댓글id, 작성자id, 댓글 내용
- 댓글 삭제
게시글 id, 댓글id, 작성자id
- 댓글 추천/비추천
게시글id, 댓글id, 사용자id

**Comment by MayoneJY** [comment]
다음 게시글/이전게시글 : NavigateViewDTO를 참조하여 이전 게시글과 다음 게시글이 존재하는지 여부를 게시판 종류도 함께 받아서 조회하는 SQL문을 만들어주세요 (게시판 종류 : 전체/공지사항/튜터링/자유게시판, 전체 값은 0으로 전달받는걸로)

이 부분은 수정해야할 것 같습니다.
ViewResponseDTO를 리턴해주는 것이 아닌 postIndex를 리턴을 해주셔야 합니다.

**Comment by MayoneJY** [comment]
그리고 몇몇 클래스가 카멜기법이 아닌 스네이크 기법으로 되어있고, 룸북이 적용이 안되어 있던데 주의해주세용
또 DTO는 왠만하면 DB 컬럼명과 일치 시켜주세요 틀린 것들이 꽤나 있었습니다.

**Comment by YeChanKang** [comment]
> 다음 게시글/이전게시글 : NavigateViewDTO를 참조하여 이전 게시글과 다음 게시글이 존재하는지 여부를 게시판 종류도 함께 받아서 조회하는 SQL문을 만들어주세요 (게시판 종류 : 전체/공지사항/튜터링/자유게시판, 전체 값은 0으로 전달받는걸로)
> 
> 이 부분은 수정해야할 것 같습니다. ViewResponseDTO를 리턴해주는 것이 아닌 postIndex를 리턴을 해주셔야 합니다.

예. 생각하신 대로 postIndex를 반환하는게 맞습니다.
그 postIndex를 토대로 DAO단에서 다시 getPost를 사용해서 ViewResponseDTO를 리턴할 생각입니다

**Comment by YeChanKang** [comment]
> 그리고 몇몇 클래스가 카멜기법이 아닌 스네이크 기법으로 되어있고, 룸북이 적용이 안되어 있던데 주의해주세용 또 DTO는 왠만하면 DB 컬럼명과 일치 시켜주세요 틀린 것들이 꽤나 있었습니다.

혹시 어떤 클래스가 스네이크 기법으로 되어있을까요?
롬복은 수정하도록 하겠습니다.
컬럼명과 일치시키는 작업은 지금 바로는 어려울 것 같습니다.

**Comment by MayoneJY** [comment]
> > 다음 게시글/이전게시글 : NavigateViewDTO를 참조하여 이전 게시글과 다음 게시글이 존재하는지 여부를 게시판 종류도 함께 받아서 조회하는 SQL문을 만들어주세요 (게시판 종류 : 전체/공지사항/튜터링/자유게시판, 전체 값은 0으로 전달받는걸로)
> > 이 부분은 수정해야할 것 같습니다. ViewResponseDTO를 리턴해주는 것이 아닌 postIndex를 리턴을 해주셔야 합니다.
> 
> 예. 생각하신 대로 postIndex를 반환하는게 맞습니다. 그 postIndex를 토대로 DAO단에서 다시 getPost를 사용해서 ViewResponseDTO를 리턴할 생각입니다

아뇨, 최종 반환하는 것이 postIndex라는 것입니다. 다음 게시글을 눌렀을 때 postIndex만 불러와서 주소를 바꿔주면 post페이지에서 post정보를 호출할 것입니다. DTO를 리턴을 하게 되면 정보를 두 번 불러오는 일이 발생합니다.

**Comment by MayoneJY** [comment]
> > 그리고 몇몇 클래스가 카멜기법이 아닌 스네이크 기법으로 되어있고, 룸북이 적용이 안되어 있던데 주의해주세용 또 DTO는 왠만하면 DB 컬럼명과 일치 시켜주세요 틀린 것들이 꽤나 있었습니다.
> 
> Comment...DTO들의 변수명이 스네이크 기법으로 되어있던 것을 수정했습니다 롬복 누락된 DTO들 수정했습니다 컬럼명과 일치시키는 작업은 지금 바로는 어려울 것 같습니다.

다음 부터는 일치 시켜주세요 현재 DTO에 대한 속성명에 맞춰 mapper 제작했습니다.

**Comment by YeChanKang** [comment]
> > > 다음 게시글/이전게시글 : NavigateViewDTO를 참조하여 이전 게시글과 다음 게시글이 존재하는지 여부를 게시판 종류도 함께 받아서 조회하는 SQL문을 만들어주세요 (게시판 종류 : 전체/공지사항/튜터링/자유게시판, 전체 값은 0으로 전달받는걸로)
> > > 이 부분은 수정해야할 것 같습니다. ViewResponseDTO를 리턴해주는 것이 아닌 postIndex를 리턴을 해주셔야 합니다.
> > 
> > 
> > 예. 생각하신 대로 postIndex를 반환하는게 맞습니다. 그 postIndex를 토대로 DAO단에서 다시 getPost를 사용해서 ViewResponseDTO를 리턴할 생각입니다
> 
> 아뇨, 최종 반환하는 것이 postIndex라는 것입니다. 다음 게시글을 눌렀을 때 postIndex만 불러와서 주소를 바꿔주면 post페이지에서 post정보를 호출할 것입니다. DTO를 리턴을 하게 되면 정보를 두 번 불러오는 일이 발생합니다.

이해했습니다. 그럼 다음 인덱스, 이전 인덱스가 존재하면 반환하는 sql문만 만들어주세요.

**Comment by YeChanKang** [comment]
> > > 그리고 몇몇 클래스가 카멜기법이 아닌 스네이크 기법으로 되어있고, 룸북이 적용이 안되어 있던데 주의해주세용 또 DTO는 왠만하면 DB 컬럼명과 일치 시켜주세요 틀린 것들이 꽤나 있었습니다.
> > 
> > 
> > Comment...DTO들의 변수명이 스네이크 기법으로 되어있던 것을 수정했습니다 롬복 누락된 DTO들 수정했습니다 컬럼명과 일치시키는 작업은 지금 바로는 어려울 것 같습니다.
> 
> 다음 부터는 일치 시켜주세요 현재 DTO에 대한 속성명에 맞춰 mapper 제작했습니다.

넵 최종적으로 병합하기 전에 다시 맞추도록 하겠습니다
